# Generated by GH Copilot

output "cosmos_db_account_id" {
  description = "The ID of the Cosmos DB account"
  value       = azurerm_cosmosdb_account.cosmos_db.id
}

output "cosmos_db_account_name" {
  description = "The name of the Cosmos DB account"
  value       = azurerm_cosmosdb_account.cosmos_db.name
}

output "cosmos_db_account_endpoint" {
  description = "The endpoint of the Cosmos DB account"
  value       = azurerm_cosmosdb_account.cosmos_db.endpoint
}

output "cosmos_db_account_connection_strings" {
  description = "The connection strings of the Cosmos DB account"
  value       = azurerm_cosmosdb_account.cosmos_db.connection_strings
  sensitive   = true
}

output "cosmos_db_sql_database_id" {
  description = "The ID of the SQL Database within the Cosmos DB account"
  value       = azurerm_cosmosdb_sql_database.sql_db.id
}
