# Generated by GH Copilot

variable "resource_group_name" {
  description = "The name of the resource group"
  type        = string
}

variable "location" {
  description = "The location of the resources"
  type        = string
  default     = "eastus2"
}

variable "cosmos_db_account_name" {
  description = "The name of the Cosmos DB account"
  type        = string
}

variable "cosmos_db_sql_database_name" {
  description = "The name of the SQL Database within the Cosmos DB account"
  type        = string
  default     = "defaultdb"
}

variable "tags" {
  description = "Tags for the resources"
  type        = map(string)
  default     = {}
}
