# Generated by GH Copilot

output "storage_account_id" {
  description = "The ID of the storage account"
  value       = azurerm_storage_account.storage_account.id
}

output "storage_account_name" {
  description = "The name of the storage account"
  value       = azurerm_storage_account.storage_account.name
}

output "storage_account_primary_access_key" {
  description = "The primary access key of the storage account"
  value       = azurerm_storage_account.storage_account.primary_access_key
  sensitive   = true
}

output "storage_account_primary_connection_string" {
  description = "The primary connection string of the storage account"
  value       = azurerm_storage_account.storage_account.primary_connection_string
  sensitive   = true
}

output "storage_container_name" {
  description = "The name of the storage container"
  value       = azurerm_storage_container.storage_container.name
}
