# Generated by GH Copilot

variable "resource_group_name" {
  description = "The name of the resource group"
  type        = string
}

variable "location" {
  description = "The location of the resources"
  type        = string
  default     = "eastus2"
}

variable "storage_account_name" {
  description = "The name of the storage account"
  type        = string
}

variable "storage_container_name" {
  description = "The name of the storage container"
  type        = string
  default     = "data"
}

variable "tags" {
  description = "Tags for the resources"
  type        = map(string)
  default     = {}
}
