# Generated by GH Copilot

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
  required_version = ">= 1.0.0"
}

provider "azurerm" {
  features {}
}

# Resource Group
module "resource_group" {
  source = "./modules/resource_group"

  resource_group_name = var.resource_group_name
  location            = var.location
  tags                = var.tags
}

# App Service
module "app_service" {
  source = "./modules/app_service"
  
  resource_group_name   = module.resource_group.resource_group_name
  location              = module.resource_group.resource_group_location
  app_service_plan_name = var.app_service_plan_name
  app_service_name      = var.app_service_name
  tags                  = var.tags

  depends_on = [module.resource_group]
}

# Cosmos DB
module "cosmos_db" {
  source = "./modules/cosmos_db"
  
  resource_group_name         = module.resource_group.resource_group_name
  location                    = module.resource_group.resource_group_location
  cosmos_db_account_name      = var.cosmos_db_account_name
  cosmos_db_sql_database_name = var.cosmos_db_sql_database_name
  tags                        = var.tags

  depends_on = [module.resource_group]
}

# Storage Account
module "storage_account" {
  source = "./modules/storage_account"
  
  resource_group_name     = module.resource_group.resource_group_name
  location                = module.resource_group.resource_group_location
  storage_account_name    = var.storage_account_name
  storage_container_name  = var.storage_container_name
  tags                    = var.tags

  depends_on = [module.resource_group]
}
