# Generated by GH Copilot

variable "resource_group_name" {
  description = "The name of the resource group"
  type        = string
  default     = "rg-azure-app-infra"
}

variable "location" {
  description = "The location of the resources"
  type        = string
  default     = "eastus2"
}

variable "tags" {
  description = "Tags for the resources"
  type        = map(string)
  default     = {
    Environment = "Development"
    ManagedBy   = "Terraform"
    Project     = "AzureAppInfra"
  }
}

variable "app_service_plan_name" {
  description = "The name of the App Service Plan"
  type        = string
  default     = "asp-azure-app"
}

variable "app_service_name" {
  description = "The name of the App Service"
  type        = string
  default     = "app-azure-app"
}

variable "cosmos_db_account_name" {
  description = "The name of the Cosmos DB account"
  type        = string
  default     = "cosmos-azure-app"
}

variable "cosmos_db_sql_database_name" {
  description = "The name of the SQL Database within the Cosmos DB account"
  type        = string
  default     = "appdb"
}

variable "storage_account_name" {
  description = "The name of the storage account"
  type        = string
  default     = "stazureapp"
}

variable "storage_container_name" {
  description = "The name of the storage container"
  type        = string
  default     = "data"
}
